### ISSUE TITLE
Item highlighted on the Cell List sometimes does not match with displayed item on the main page

### ISSUE THREAD

**Issue by dixonsiu** [personium/app-uc-unit-manager#5]

**Comment by yoh1496** [comment]
Isn't this resolved yet? Could you write how to reproduce this?

**Comment by dixonsiu** [comment]
When you delete a cell, the next displayed cell will not be correct. You have to select ia specific cell.

**Comment by dixonsiu** [comment]
Cannot reproduce in current version.
