### ISSUE TITLE
Cell name is wrongly validated

### ISSUE THREAD

**Issue by dixonsiu** [personium/app-uc-unit-manager#91]
Not only it is [wrongly encoded](https://github.com/personium/app-uc-unit-manager/blob/master/src/js/cellProfile.js#L104), it is also wrong in logic.  

Correct specification [here](https://personium.io/docs/ja/apiref/current/100_Create_Cell.html)

**Comment by csKyou** [comment]
close

**Comment by csKyou** [comment]
close #91

**Comment by csKyou** [comment]
Close #91
